### PR TITLE
Search bar functionality

### PR DESCRIPTION
**Pull request by nelliott82**
- Search functionality that searches performers and events by keyword
- Conditionally rendered search results
- Added search function to apiMasters
- Changed backend port in apiMasters to point at 3001
- onClick render of Artist (but id not leveraged)

TODO: onClick render of Event page.

### CODE REVIEW

**Comment by nelliott82** [comment]
[:warning: User types keyword or performer name into search bar.](https://trello.com/c/OrezkQOG/35-warning-user-types-keyword-or-performer-name-into-search-bar)

**Comment by nelliott82** [comment]
[:warning: Logged in user clicks an Add/Follow button for Busker from Buskers list view and adds Busker to follow list. Anonymous user is redirected to Log In page/screen/modal.](https://trello.com/c/r7AC8dP6/20-warning-logged-in-user-clicks-an-add-follow-button-for-busker-from-buskers-list-view-and-adds-busker-to-follow-list-anonymous-us)

**Comment by nelliott82** [comment]
[:warning: User clicks on an Artist or Event in the Search results and navigates to the Artist or Event page.](https://trello.com/c/JwutewB9/36-warning-user-clicks-on-an-artist-or-event-in-the-search-results-and-navigates-to-the-artist-or-event-page)

**Review by Yuki-OG — APPROVED** [review]
This is so cool! Amazing work as always

**Pull request merged**
